pipeline{

    agent any

    stages{

        stage('Verify shell env'){
            steps{
                script{
                    def jobName = env.JOB_NAME
                    def buildNumber = env.BUILD_NUMBER

                    echo "Job Name: $jobName"
                    echo "Build Number: $buildNumber"

                    sh 'sudo docker --version'
                    sh 'sudo dotnet --info'
                }
            }
        }
        stage('Build the dotnet project'){
            steps{
                sh 'chmod 755 ./jenkins-plugin-model/ci/01-build.sh && ./jenkins-plugin-model/ci/01-build.sh'
            }
        }

        stage('Run the unit tests and publish'){
            steps{
                sh 'chmod 755 ./jenkins-plugin-model/ci/03-unit-test.sh && ./jenkins-plugin-model/ci/03-unit-test.sh'
                mstest testResultsFile: '**/*.trx'
            }
        }

        stage('Build docker image and push to docker hub'){
            steps{
                script{
                    def buildNumber = env.BUILD_NUMBER
                    withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'DOCKER_HUB_PASSWORD', usernameVariable: 'DOCKER_HUB_USER')]) {
                        sh "chmod 755 ./jenkins-plugin-model/ci/04-push.sh && ./jenkins-plugin-model/ci/04-push.sh $buildNumber"
                    }
                }
            }
        }
    }
}