pipeline {
    agent any

    environment {
        MY_ENV_VAR = 'Custom value'
    }

    stages {
        stage('checkout') {
            steps {
                script {
                    def gitRepoUrl = 'https://github.com/Neeraj-Sharma-902/jenkins-sample-project.git'

                    checkout poll: false,
                             scm: scmGit(branches: [[name: '*/master']],
                                         extensions: [cloneOption(depth: 1, noTags: false, reference: '', shallow: true),
                                                      cleanBeforeCheckout(deleteUntrackedNestedRepositories: true)],
                                                      userRemoteConfigs: [[url: gitRepoUrl]])
                }
            }
        }

        stage('Build Stage'){
            steps{
                echo "Build Step"
            }
        }

        stage('Unit Test Stage'){
            steps{
                echo "Unit Tests"
            }
        }

        stage('Deploy Stage'){
            steps{
                echo "My environment variable value is : $MY_ENV_VAR"
            }
        }
    }

    post{
        success{
            echo "pipeline succeeded"
        }
        failure{
            echo "Pipeline failed"
        }
    }
}
